
FROM unit:python3.11

ENV workdir=/home/app
ENV DJANGO_PROJECT_NAME=test_app
ENV hostname=www.exemple.com

RUN mkdir -p /home/app/test_app

COPY test_app /home/app/test_app

COPY django.config /etc/unit/django.config

COPY run.sh /run.sh

RUN chmod +x /run.sh && \
    apt-get update -y; \  
    apt-get update --no-cache-dir -y; \
    apt-get -o APT::Install-Recommends=false upgrade; \
    mkdir -p /home/app/test_app/static; \
    pip install --upgrade pip && \
    pip install -r /home/app/test_app/requirements.txt && \
    pip install uvicorn && \
    python3 /home/app/test_app/manage.py collectstatic --noinput

RUN apt-get remove --purge pip && \
    apt-get autoremove

EXPOSE 8000

CMD ["./run.sh"]
